// Daily Wrap — headlines, yesterday's scores, today's games.
// No API keys required: headlines come from headlines.json, generated by a
// scheduled GitHub Actions workflow (scripts/fetch-headlines.js) that fetches
// public RSS feeds server-side, where CORS doesn't apply. Sports data comes
// from ESPN's public scoreboard API, fetched directly from the browser.

// Fallback only — see fetchWithFallback, which tries the URL directly first
// and only reaches for these if that fails. ESPN allows cross-origin
// requests, so its scoreboard calls succeed direct and rarely need these.
const CORS_PROXIES = [
  (url) => `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,
  (url) => `https://api.codetabs.com/v1/proxy?quest=${encodeURIComponent(url)}`,
  // corsproxy.io removed: returned 403 on every single request (confirmed in
  // a browser console log, 2026-07-29) — a guaranteed-failing branch.
];

// Grouped by sport so the site stays organized even on days when only one
// sport has games (e.g. baseball-only stretches of the calendar). Covers the
// leagues with the heaviest US betting volume; a category with no games that
// day auto-collapses (see renderLeagueGroups) rather than disappearing.
// `siteSport` is the espn.com URL segment used to link team/fighter names to
// their real ESPN page (stats, roster, full schedule) instead of building a
// second copy of that here.
const LEAGUES = [
  { id: 'nfl', name: 'NFL', path: 'football/nfl', group: 'Football', siteSport: 'nfl' },
  { id: 'ncaaf', name: 'College Football', path: 'football/college-football', group: 'Football', siteSport: 'college-football' },
  { id: 'nba', name: 'NBA', path: 'basketball/nba', group: 'Basketball', siteSport: 'nba' },
  { id: 'wnba', name: 'WNBA', path: 'basketball/wnba', group: 'Basketball', siteSport: 'wnba' },
  { id: 'ncaab', name: 'College Basketball', path: 'basketball/mens-college-basketball', group: 'Basketball', siteSport: 'mens-college-basketball' },
  { id: 'mlb', name: 'MLB', path: 'baseball/mlb', group: 'Baseball', siteSport: 'mlb' },
  { id: 'nhl', name: 'NHL', path: 'hockey/nhl', group: 'Hockey', siteSport: 'nhl' },
  { id: 'epl', name: 'Premier League', path: 'soccer/eng.1', group: 'Soccer', siteSport: 'soccer' },
  { id: 'ucl', name: 'Champions League', path: 'soccer/uefa.champions', group: 'Soccer', siteSport: 'soccer' },
  { id: 'uel', name: 'Europa League', path: 'soccer/uefa.europa', group: 'Soccer', siteSport: 'soccer' },
  { id: 'laliga', name: 'La Liga', path: 'soccer/esp.1', group: 'Soccer', siteSport: 'soccer' },
  { id: 'seriea', name: 'Serie A', path: 'soccer/ita.1', group: 'Soccer', siteSport: 'soccer' },
  { id: 'bundesliga', name: 'Bundesliga', path: 'soccer/ger.1', group: 'Soccer', siteSport: 'soccer' },
  { id: 'ligue1', name: 'Ligue 1', path: 'soccer/fra.1', group: 'Soccer', siteSport: 'soccer' },
  { id: 'mls', name: 'MLS', path: 'soccer/usa.1', group: 'Soccer', siteSport: 'soccer' },
  { id: 'ufc', name: 'UFC', path: 'mma/ufc', group: 'Combat Sports', siteSport: 'mma' },
  // Boxing removed: ESPN returns a genuine HTTP 400 for the 'boxing/boxing'
  // path (direct, not via a proxy — confirmed in a browser console log), so
  // it only ever produced errors. No verified correct path to swap in.
];

const today = new Date();
const yesterday = new Date(today);
yesterday.setDate(today.getDate() - 1);
const tomorrow = new Date(today);
tomorrow.setDate(today.getDate() + 1);

function pad(n) { return String(n).padStart(2, '0'); }
function toYYYYMMDD(d) { return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}`; }
function longDate(d) { return d.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }); }

// A direct attempt either succeeds quickly or fails fast on CORS, so it gets
// a short leash; the free proxies are slower and get a longer one.
const DIRECT_TIMEOUT_MS = 6000;
const PROXY_TIMEOUT_MS = 20000;

async function fetchWithTimeout(url, timeoutMs = DIRECT_TIMEOUT_MS) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, { signal: controller.signal });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return res;
  } finally {
    clearTimeout(timer);
  }
}

async function fetchWithFallback(url) {
  // Direct first, on its own — ESPN allows cross-origin requests, so this
  // succeeds for essentially every call and the proxies below go unused.
  try {
    const res = await fetchWithTimeout(url);
    return await res.json();
  } catch {
    // Fall through to the proxies for the rare direct failure.
  }

  const attempts = CORS_PROXIES.map((makeProxyUrl) =>
    fetchWithTimeout(makeProxyUrl(url), PROXY_TIMEOUT_MS).then((res) => res.json())
  );
  try {
    return await Promise.any(attempts);
  } catch (aggregateErr) {
    throw aggregateErr.errors?.[0] || aggregateErr;
  }
}

// ---------- Headlines ----------

function relativeTime(ts) {
  const mins = Math.round((Date.now() - ts) / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins} min ago`;
  const hours = Math.round(mins / 60);
  if (hours < 24) return `${hours} hr ago`;
  const days = Math.round(hours / 24);
  return `${days} day${days === 1 ? '' : 's'} ago`;
}

function escapeAttr(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function escapeHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function renderSourceBody(source) {
  const items = source.items || [];
  if (items.length === 0) return '<p class="empty">Couldn\'t load.</p>';
  const staleNote = !source.ok && source.updatedAt
    ? `<p class="empty">Saved copy from ${relativeTime(new Date(source.updatedAt).getTime())} — couldn't refresh just now.</p>`
    : '';
  const modelName = getAiModelName();
  return staleNote + '<ul class="headline-list">' + items.map((it) => {
    const titleAttr = escapeAttr(it.title);
    const sourceAttr = escapeAttr(source.name);
    const linkAttr = escapeAttr(it.link);
    return `<li class="headline-item">
      <a href="${it.link}" target="_blank" rel="noopener noreferrer" class="headline-link">${escapeHtml(it.title)}</a>
      <button class="ask-gemini-btn" data-title="${titleAttr}" data-source="${sourceAttr}" data-link="${linkAttr}" title="Ask ${modelName} about this headline">
        <span class="sparkle-icon">✨</span> Ask ${modelName}
      </button>
    </li>`;
  }).join('') + '</ul>';
}

async function loadHeadlines() {
  const container = document.getElementById('headlines-list');
  const sub = document.getElementById('headlines-sub');
  sub.textContent = longDate(today);
  container.innerHTML = '<p class="loading">Loading headlines…</p>';

  let data;
  try {
    const res = await fetch('headlines.json', { cache: 'no-store' });
    const contentType = res.headers.get('content-type') || '';
    if (!res.ok || contentType.includes('text/html')) {
      throw new Error(`Invalid response for headlines.json: status ${res.status}, type ${contentType}`);
    }
    data = await res.json();
  } catch (err) {
    console.warn('headlines.json not directly available, attempting refresh API:', err);
    try {
      const refreshRes = await fetch('/api/refresh-headlines', { method: 'POST' });
      if (refreshRes.ok) {
        data = await refreshRes.json();
        if (data.message && !data.sources) {
          const res2 = await fetch('headlines.json', { cache: 'no-store' });
          data = await res2.json();
        }
      }
    } catch (refreshErr) {
      console.warn('Failed to refresh headlines via API:', refreshErr);
    }
  }

  if (!data || !data.sources || data.sources.length === 0) {
    container.innerHTML = '<p class="error">Couldn\'t load headlines right now. Try refreshing the page.</p>';
    return;
  }

  container.innerHTML = '';
  for (const source of data.sources || []) {
    const el = document.createElement('details');
    el.className = 'source-group';
    if ((source.items || []).length > 0) el.open = true;
    el.innerHTML = `<summary><h3>${source.name}</h3></summary>` +
      `<div class="source-group-body">${renderSourceBody(source)}</div>`;
    container.appendChild(el);
  }
}

// ---------- Sports ----------

// A competitor is either a team (most sports) or an athlete (fights). Either
// way, link its name to the real ESPN page for that team/fighter — building
// and keeping our own stats/roster pages in sync would be its own project.
function extractParticipant(c, league) {
  const isAthlete = !!c.athlete && !c.team;
  const entity = c.team || c.athlete;
  const name = entity?.displayName || entity?.shortDisplayName || entity?.name || 'TBD';
  const link = entity?.id
    ? `https://www.espn.com/${league.siteSport}/${isAthlete ? 'player' : 'team'}/_/id/${entity.id}`
    : null;
  return { name, score: c.score, link };
}

function formatML(val) {
  if (!val || val === 'OFF') return val;
  const num = parseInt(val, 10);
  if (!isNaN(num) && num > 0) return `+${num}`;
  return `${val}`;
}

function parseOdds(comp, eventSummary = null) {
  const oddsArr = comp?.odds || [];
  const primaryOdds = oddsArr[0] || eventSummary?.pickcenter?.[0] || null;
  if (!primaryOdds && !eventSummary?.winprobability) return null;

  const providerName = primaryOdds?.provider?.displayName || 'DraftKings';
  let providerLink = primaryOdds?.link?.href || null;
  if (!providerLink && Array.isArray(primaryOdds?.links)) {
    const gameLink = primaryOdds.links.find(l => l.rel?.includes('game') || l.rel?.includes('main') || l.rel?.includes('desktop'));
    if (gameLink) providerLink = gameLink.href;
  }

  const details = primaryOdds?.details || '';
  const overUnder = primaryOdds?.overUnder ? `O/U ${primaryOdds.overUnder}` : '';
  const spread = primaryOdds?.spread ? (primaryOdds.spread > 0 ? `+${primaryOdds.spread}` : `${primaryOdds.spread}`) : '';

  const ml = primaryOdds?.moneyline || {};
  const openHomeML = ml.home?.open?.odds;
  const openAwayML = ml.away?.open?.odds;

  const homeTeamOddsML = primaryOdds?.homeTeamOdds?.moneyLine !== undefined ? String(primaryOdds.homeTeamOdds.moneyLine) : null;
  const awayTeamOddsML = primaryOdds?.awayTeamOdds?.moneyLine !== undefined ? String(primaryOdds.awayTeamOdds.moneyLine) : null;

  const closeHomeML = ml.home?.close?.odds || ml.home?.open?.odds || homeTeamOddsML;
  const closeAwayML = ml.away?.close?.odds || ml.away?.open?.odds || awayTeamOddsML;
  const closeDrawML = ml.draw?.close?.odds || ml.draw?.open?.odds;

  const liveHomeML = ml.home?.live?.odds;
  const liveAwayML = ml.away?.live?.odds;
  const liveDrawML = ml.draw?.live?.odds;

  const ps = primaryOdds?.pointSpread || {};
  const homeSpreadLine = ps.home?.close?.line || ps.home?.open?.line;
  const homeSpreadOdds = ps.home?.close?.odds || ps.home?.open?.odds;
  const awaySpreadLine = ps.away?.close?.line || ps.away?.open?.line;
  const awaySpreadOdds = ps.away?.close?.odds || ps.away?.open?.odds;

  let winProb = null;
  if (eventSummary?.winprobability && eventSummary.winprobability.length > 0) {
    const lastWp = eventSummary.winprobability[eventSummary.winprobability.length - 1];
    if (typeof lastWp.homeWinPercentage === 'number') {
      winProb = Math.round(lastWp.homeWinPercentage * 100);
    }
  }

  return {
    providerName,
    providerLink,
    details,
    overUnder,
    spread,
    openHomeML,
    openAwayML,
    closeHomeML,
    closeAwayML,
    closeDrawML,
    liveHomeML,
    liveAwayML,
    liveDrawML,
    homeSpread: homeSpreadLine ? `${homeSpreadLine}${homeSpreadOdds ? ` (${formatML(homeSpreadOdds)})` : ''}` : '',
    awaySpread: awaySpreadLine ? `${awaySpreadLine}${awaySpreadOdds ? ` (${formatML(awaySpreadOdds)})` : ''}` : '',
    winProb,
  };
}

function normalizeEvent(ev, league, eventSummary = null) {
  const comp = ev.competitions?.[0];
  const statusType = comp?.status?.type || {};
  const competitors = comp?.competitors || [];
  const home = competitors.find((c) => c.homeAway === 'home') || competitors[0];
  const away = competitors.find((c) => c.homeAway === 'away') || competitors[1];
  return {
    date: ev.date,
    state: statusType.state, // 'pre' | 'in' | 'post'
    completed: !!statusType.completed,
    statusDetail: statusType.shortDetail || statusType.detail || '',
    home: home ? extractParticipant(home, league) : null,
    away: away ? extractParticipant(away, league) : null,
    odds: parseOdds(comp, eventSummary),
  };
}

async function fetchScoreboard(league, date) {
  const url = `https://site.api.espn.com/apis/site/v2/sports/${league.path}/scoreboard?dates=${toYYYYMMDD(date)}`;
  try {
    const data = await fetchWithFallback(url);
    const rawEvents = data.events || [];
    
    // Fetch summary for live games ('in'), completed games ('post'), or events lacking direct odds
    const normalized = await Promise.all(
      rawEvents.map(async (ev) => {
        const comp = ev.competitions?.[0];
        const state = comp?.status?.type?.state;
        let summary = null;
        if (state === 'in' || state === 'post' || !comp?.odds?.length) {
          try {
            summary = await fetchWithFallback(
              `https://site.api.espn.com/apis/site/v2/sports/${league.path}/summary?event=${ev.id}`
            );
          } catch {
            // Fall back to scoreboard-level data if summary fetch fails
          }
        }
        return normalizeEvent(ev, league, summary);
      })
    );
    return normalized;
  } catch (err) {
    console.warn(`Scoreboard fetch failed for ${league.name}:`, err);
    return null; // signals a failed fetch, distinct from "no games"
  }
}

function groupBy(list, keyFn) {
  const map = new Map();
  for (const item of list) {
    const key = keyFn(item);
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(item);
  }
  return map;
}

function renderLeagueGroups(container, leagueResults, renderGame, emptyLabel) {
  if (leagueResults.every((r) => r.events === null)) {
    container.innerHTML = '<p class="error">Couldn\'t load sports data right now. Try refreshing the page.</p>';
    return;
  }

  const byGroup = groupBy(leagueResults, (r) => r.league.group);
  container.innerHTML = '';
  for (const [groupName, leagues] of byGroup) {
    const hasGames = leagues.some((r) => r.events && r.events.length > 0);
    const groupEl = document.createElement('details');
    groupEl.className = 'league-group';
    if (hasGames) groupEl.open = true;
    let groupHtml = `<summary><h3>${groupName}</h3></summary><div class="league-group-body"><ul class="game-list">`;
    for (const { league, events } of leagues) {
      if (events === null) {
        groupHtml += `<li class="game-row muted-row"><div class="game-main"><span class="team-name">${league.name}</span><span class="game-status">Couldn't load</span></div></li>`;
      } else if (events.length === 0) {
        groupHtml += `<li class="game-row muted-row"><div class="game-main"><span class="team-name">${league.name}</span><span class="game-status">${emptyLabel}</span></div></li>`;
      } else {
        groupHtml += events.map((ev) => renderGame(ev, league)).join('');
      }
    }
    groupHtml += `</ul></div>`;
    groupEl.innerHTML = groupHtml;
    container.appendChild(groupEl);
  }
}

function nameHtml(participant) {
  return participant.link
    ? `<a href="${participant.link}" target="_blank" rel="noopener noreferrer">${participant.name}</a>`
    : participant.name;
}

function renderOddsBar(ev) {
  const o = ev.odds;
  if (!o) return '';

  let html = `<div class="game-odds-container">`;

  if (ev.state === 'in') {
    const isOff = o.liveHomeML === 'OFF' || o.liveAwayML === 'OFF';
    const hasLiveML = o.liveHomeML && o.liveAwayML && !isOff;

    html += `<div class="odds-bar live-odds-bar">`;
    html += `<span class="odds-badge live-badge">● LIVE ODDS</span>`;

    if (hasLiveML) {
      const awayML = formatML(o.liveAwayML);
      const homeML = formatML(o.liveHomeML);
      const drawML = o.liveDrawML ? ` · Draw ${formatML(o.liveDrawML)}` : '';
      html += `<span class="odds-chip live-ml-chip">Live ML: <b>${ev.away?.name || 'Away'}: ${awayML}</b> · <b>${ev.home?.name || 'Home'}: ${homeML}</b>${drawML}</span>`;
    } else if (isOff) {
      html += `<span class="odds-chip muted-chip">Live Odds: Board Locked</span>`;
    }

    if (o.winProb !== null && o.winProb !== undefined) {
      html += `<span class="odds-chip win-prob-chip">Win Prob: <b>${ev.home?.name || 'Home'} ${o.winProb}%</b></span>`;
    }

    const openMLStr = (o.openAwayML && o.openHomeML) 
      ? `Open ML: ${formatML(o.openAwayML)} / ${formatML(o.openHomeML)}`
      : ((o.closeAwayML && o.closeHomeML) ? `Line ML: ${formatML(o.closeAwayML)} / ${formatML(o.closeHomeML)}` : '');
    const lineStr = o.details ? `Line: ${o.details}` : '';
    const ouStr = o.overUnder ? `${o.overUnder}` : '';
    const preParts = [lineStr, openMLStr, ouStr].filter(Boolean).join(' · ');

    if (preParts) {
      html += `<span class="odds-chip pre-compare-chip">Pre-Game: ${preParts}</span>`;
    }

    html += `</div>`;
  } else {
    const isPost = ev.state === 'post';
    html += `<div class="odds-bar ${isPost ? 'post-odds-bar' : 'pre-odds-bar'}">`;
    
    if (isPost) {
      html += `<span class="odds-badge post-badge">Pregame Line</span>`;
    } else if (o.providerName) {
      const providerContent = o.providerLink
        ? `<a href="${o.providerLink}" target="_blank" rel="noopener noreferrer" class="odds-provider-link">${o.providerName} ↗</a>`
        : o.providerName;
      html += `<span class="odds-badge provider-badge">${providerContent}</span>`;
    }

    if (o.details) {
      html += `<span class="odds-chip highlight-chip">Line: <b>${o.details}</b></span>`;
    }

    if (o.closeAwayML && o.closeHomeML) {
      const awayMLVal = formatML(o.closeAwayML);
      const homeMLVal = formatML(o.closeHomeML);
      const drawMLVal = o.closeDrawML ? ` / Draw ${formatML(o.closeDrawML)}` : '';
      html += `<span class="odds-chip ml-chip">ML: <b>${ev.away?.name || 'Away'} ${awayMLVal}</b> / <b>${ev.home?.name || 'Home'} ${homeMLVal}</b>${drawMLVal}</span>`;
    }

    if (o.awaySpread && o.homeSpread) {
      html += `<span class="odds-chip spread-chip">Spread: <b>${o.awaySpread}</b> / <b>${o.homeSpread}</b></span>`;
    }

    if (o.overUnder) {
      html += `<span class="odds-chip ou-chip"><b>${o.overUnder}</b></span>`;
    }

    html += `</div>`;
  }

  html += `</div>`;
  return html;
}

function renderYesterdayGame(ev, league) {
  if (!ev.completed) return '';
  const away = ev.away, home = ev.home;
  return `<li class="game-row">
    <div class="game-main">
      <div class="game-teams">
        <div class="team-row"><span class="team-name">${league.name} · ${nameHtml(away)}</span><span class="team-score">${away.score}</span></div>
        <div class="team-row"><span class="team-name">${nameHtml(home)}</span><span class="team-score">${home.score}</span></div>
      </div>
      <span class="game-status">${ev.statusDetail || 'Final'}</span>
    </div>
    ${renderOddsBar(ev)}
  </li>`;
}

function renderScheduledGame(ev, league) {
  const away = ev.away, home = ev.home;
  const time = new Date(ev.date).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
  let statusHtml;
  if (ev.state === 'in') {
    statusHtml = `<span class="game-status live">${ev.statusDetail || 'Live'}</span>`;
  } else if (ev.state === 'post') {
    statusHtml = `<span class="game-status">${ev.statusDetail || 'Final'}</span>`;
  } else {
    statusHtml = `<span class="game-status">${time}</span>`;
  }
  const showScores = ev.state !== 'pre';
  return `<li class="game-row">
    <div class="game-main">
      <div class="game-teams">
        <div class="team-row"><span class="team-name">${league.name} · ${nameHtml(away)}</span>${showScores ? `<span class="team-score">${away.score}</span>` : ''}</div>
        <div class="team-row"><span class="team-name">${nameHtml(home)}</span>${showScores ? `<span class="team-score">${showScores ? home.score : ''}</span>` : ''}</div>
      </div>
      ${statusHtml}
    </div>
    ${renderOddsBar(ev)}
  </li>`;
}

async function loadYesterdayScores() {
  document.getElementById('yesterday-date').textContent = longDate(yesterday);
  const container = document.getElementById('yesterday-scores-list');
  const results = await Promise.all(LEAGUES.map(async (league) => {
    const events = await fetchScoreboard(league, yesterday);
    const completed = events ? events.filter((e) => e.completed) : null;
    return { league, events: completed };
  }));
  renderLeagueGroups(container, results, renderYesterdayGame, 'No games');
}

async function loadGamesFor(dateLabelId, listId, date) {
  document.getElementById(dateLabelId).textContent = longDate(date);
  const container = document.getElementById(listId);
  const results = await Promise.all(LEAGUES.map(async (league) => {
    const events = await fetchScoreboard(league, date);
    return { league, events };
  }));
  renderLeagueGroups(container, results, renderScheduledGame, 'No games scheduled');
}

async function loadTodayGames() {
  await loadGamesFor('today-date', 'today-games-list', today);
}

async function loadTomorrowGames() {
  await loadGamesFor('tomorrow-date', 'tomorrow-games-list', tomorrow);
}

// ---------- Golf Leaderboards ----------

const GOLF_TOURS = [
  { id: 'pga', name: 'PGA TOUR', path: 'golf/pga', siteSport: 'golf' },
  { id: 'lpga', name: 'LPGA Tour', path: 'golf/lpga', siteSport: 'golf' },
  { id: 'liv', name: 'LIV Golf', path: 'golf/liv', siteSport: 'golf' },
];

function formatGolfDates(startStr, endStr) {
  try {
    const s = new Date(startStr);
    const e = endStr ? new Date(endStr) : s;
    const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const startMonth = MONTHS[s.getUTCMonth()];
    const endMonth = MONTHS[e.getUTCMonth()];
    const startDay = s.getUTCDate();
    const endDay = e.getUTCDate();
    const year = e.getUTCFullYear();
    if (startMonth === endMonth) {
      return `${startMonth} ${startDay} – ${endDay}, ${year}`;
    }
    return `${startMonth} ${startDay} – ${endMonth} ${endDay}, ${year}`;
  } catch {
    return '';
  }
}

async function loadGolfLeaderboards() {
  const container = document.getElementById('golf-list');
  if (!container) return;

  const results = await Promise.all(GOLF_TOURS.map(async (tour) => {
    const url = `https://site.api.espn.com/apis/site/v2/sports/${tour.path}/scoreboard`;
    try {
      const data = await fetchWithFallback(url);
      return { tour, data };
    } catch (err) {
      console.warn(`Golf fetch failed for ${tour.name}:`, err);
      return { tour, data: null };
    }
  }));

  if (results.every((r) => r.data === null)) {
    container.innerHTML = '<p class="error">Couldn\'t load golf data right now. Try refreshing the page.</p>';
    return;
  }

  container.innerHTML = '';

  for (const { tour, data } of results) {
    const groupEl = document.createElement('details');
    groupEl.className = 'league-group golf-card';

    const events = data?.events || [];
    if (events.length > 0) groupEl.open = true;

    if (!data || events.length === 0) {
      groupEl.innerHTML = `
        <summary><div class="golf-summary-header"><h3>${tour.name}</h3><span class="game-status">Scheduled</span></div></summary>
        <div class="league-group-body">
          <p class="empty">No tournament scheduled this week.</p>
        </div>`;
      container.appendChild(groupEl);
      continue;
    }

    const event = events[0];
    const comp = event.competitions?.[0] || {};
    const statusType = comp.status?.type || event.status?.type || {};
    const isLive = statusType.state === 'in';
    const isCompleted = statusType.state === 'post' || statusType.completed;

    let statusText = '';
    let statusBadgeClass = 'game-status';
    if (isLive) {
      statusBadgeClass = 'game-status live';
      statusText = '● LIVE · ' + (statusType.detail || statusType.shortDetail || 'In Progress');
    } else if (isCompleted) {
      statusText = 'Final · ' + (statusType.detail || statusType.shortDetail || 'Complete');
    } else {
      if (event.date) {
        const startDate = new Date(event.date);
        const dateFormatted = startDate.toLocaleDateString('en-US', {
          timeZone: 'UTC',
          weekday: 'short',
          month: 'short',
          day: 'numeric'
        });
        statusText = `Scheduled · Starts ${dateFormatted}`;
      } else {
        statusText = 'Scheduled';
      }
    }

    const venue = comp.venue ? `${comp.venue.fullName || ''}${comp.venue.address?.city ? ' · ' + comp.venue.address.city : ''}` : '';
    const dateRange = event.date ? formatGolfDates(event.date, event.endDate) : '';

    const competitors = comp.competitors || [];
    const showLimit = 8;
    const tournamentId = `${tour.id}-leaderboard`;

    let html = `
      <summary>
        <div class="golf-summary-header">
          <h3>${tour.name}</h3>
          <span class="${statusBadgeClass}">${statusText}</span>
        </div>
      </summary>
      <div class="league-group-body golf-body">
        <div class="golf-tourney-meta">
          <div class="golf-tourney-title">${event.name}</div>
          <div class="golf-tourney-sub">${dateRange}${venue ? ' · ' + venue : ''}</div>
        </div>`;

    if (competitors.length === 0) {
      html += `<p class="empty" style="margin-top:0.75rem;">Field and tee times will be available closer to the tournament start.</p>`;
    } else {
      html += `
        <div class="golf-table-wrap">
          <table class="golf-table" id="${tournamentId}">
            <thead>
              <tr>
                <th class="col-pos">Pos</th>
                <th class="col-player">Player</th>
                <th class="col-score">Score</th>
                <th class="col-thru">Thru</th>
              </tr>
            </thead>
            <tbody>`;

      competitors.forEach((c, idx) => {
        const isHidden = idx >= showLimit;
        const pos = c.status?.position?.displayName || c.order || (idx + 1);
        const athlete = c.athlete || {};
        const name = athlete.displayName || athlete.fullName || 'Golfer';
        const athleteId = athlete.id || c.id;
        const link = athleteId
          ? `https://www.espn.com/golf/player/_/id/${athleteId}`
          : null;

        const playerHtml = link
          ? `<a href="${link}" target="_blank" rel="noopener noreferrer">${name}</a>`
          : name;

        const flagImg = athlete.flag?.href
          ? `<img class="golf-flag" src="${athlete.flag.href}" alt="${athlete.flag.alt || ''}" title="${athlete.flag.alt || ''}">`
          : '';

        const score = c.score || 'E';
        const scoreClass = score.startsWith('-') ? 'score-under' : (score.startsWith('+') ? 'score-over' : 'score-even');

        let thru = c.status?.type?.shortDetail || c.status?.detail || '';
        if (c.status?.period && !thru) thru = `R${c.status.period}`;

        html += `
          <tr class="golf-row ${isHidden ? 'golf-row-extra hidden' : ''}">
            <td class="col-pos">${pos}</td>
            <td class="col-player">${flagImg}${playerHtml}</td>
            <td class="col-score ${scoreClass}">${score}</td>
            <td class="col-thru">${thru}</td>
          </tr>`;
      });

      html += `</tbody></table></div>`;

      if (competitors.length > showLimit) {
        html += `
          <button type="button" class="golf-expand-btn" data-target="${tournamentId}">
            Show full field (${competitors.length} golfers)
          </button>`;
      }
    }

    html += `</div>`;
    groupEl.innerHTML = html;
    container.appendChild(groupEl);
  }

  container.querySelectorAll('.golf-expand-btn').forEach((btn) => {
    btn.addEventListener('click', (e) => {
      const targetId = e.currentTarget.getAttribute('data-target');
      const table = document.getElementById(targetId);
      if (!table) return;
      const hiddenRows = table.querySelectorAll('.golf-row-extra');
      const isExpanded = btn.classList.contains('expanded');

      hiddenRows.forEach((row) => {
        if (isExpanded) {
          row.classList.add('hidden');
        } else {
          row.classList.remove('hidden');
        }
      });

      if (isExpanded) {
        btn.classList.remove('expanded');
        const totalRows = table.querySelectorAll('tbody tr').length;
        btn.textContent = `Show full field (${totalRows} golfers)`;
      } else {
        btn.classList.add('expanded');
        btn.textContent = 'Show top 8 only';
      }
    });
  });
}

// ---------- Ask AI Handlers (Copy Prompt + Toast + Open Gemini/ChatGPT) ----------

const AI_MODEL_PREF_KEY = 'user_ai_model_pref';

function getAiModelPref() {
  const saved = localStorage.getItem(AI_MODEL_PREF_KEY);
  return (saved === 'chatgpt') ? 'chatgpt' : 'gemini';
}

function getAiModelName() {
  return getAiModelPref() === 'chatgpt' ? 'ChatGPT' : 'Gemini';
}

function updateHeadlineButtonLabels() {
  const modelName = getAiModelName();
  const buttons = document.querySelectorAll('.ask-gemini-btn');
  buttons.forEach(btn => {
    btn.title = `Ask ${modelName} about this headline`;
    btn.innerHTML = `<span class="sparkle-icon">✨</span> Ask ${modelName}`;
  });
}

function initAiModelSelect() {
  const selectEl = document.getElementById('ai-model-select');
  if (!selectEl) return;

  const currentPref = getAiModelPref();
  selectEl.value = currentPref;

  selectEl.addEventListener('change', (e) => {
    const val = e.target.value;
    localStorage.setItem(AI_MODEL_PREF_KEY, val);
    updateHeadlineButtonLabels();
  });
}

let toastTimeout = null;
function showToast(msg = 'Headline copied!') {
  const toast = document.getElementById('toast');
  const msgEl = document.getElementById('toast-message');
  if (!toast) return;

  if (msgEl) msgEl.textContent = msg;

  if (toastTimeout) clearTimeout(toastTimeout);

  toast.classList.remove('hidden', 'toast-hiding');

  toastTimeout = setTimeout(() => {
    toast.classList.add('toast-hiding');
    setTimeout(() => {
      toast.classList.add('hidden');
      toast.classList.remove('toast-hiding');
    }, 300);
  }, 3000);
}

function fallbackCopyText(text) {
  const textarea = document.createElement('textarea');
  textarea.value = text;
  textarea.style.position = 'fixed';
  textarea.style.opacity = '0';
  document.body.appendChild(textarea);
  textarea.focus();
  textarea.select();
  try {
    document.execCommand('copy');
  } catch (e) {
    console.error('Fallback copy failed', e);
  }
  document.body.removeChild(textarea);
}

function handleAskAiClick(title) {
  if (!title) return;
  const model = getAiModelPref();
  const promptText = `Please summarize and provide context for this headline: "${title}"`;

  // 1. Copy Prompt to Clipboard
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(promptText).catch(() => {
      fallbackCopyText(promptText);
    });
  } else {
    fallbackCopyText(promptText);
  }

  // 2. Show Toast Feedback
  if (model === 'chatgpt') {
    showToast('Copied! Paste into ChatGPT.');
  } else {
    showToast("Copied! Tap 'Open in App' at the top of Safari if it opens in browser.");
  }

  // 3. Open corresponding app scheme / URL in new window/tab after 500ms delay
  setTimeout(() => {
    const isMobile = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
    if (model === 'chatgpt') {
      if (isMobile) {
        window.location.href = 'chatgpt://';
        setTimeout(() => {
          window.open('https://chatgpt.com', '_blank', 'noopener,noreferrer');
        }, 800);
      } else {
        window.open('https://chatgpt.com', '_blank', 'noopener,noreferrer');
      }
    } else {
      // Gemini
      if (isMobile) {
        window.location.href = 'googleapp://';
        setTimeout(() => {
          window.open('https://gemini.google.com', '_blank', 'noopener,noreferrer');
        }, 800);
      } else {
        window.open('https://gemini.google.com', '_blank', 'noopener,noreferrer');
      }
    }
  }, 500);
}

function initAskGeminiHandlers() {
  const headlinesList = document.getElementById('headlines-list');
  if (!headlinesList) return;

  headlinesList.addEventListener('click', (e) => {
    const btn = e.target.closest('.ask-gemini-btn');
    if (btn) {
      e.preventDefault();
      e.stopPropagation();
      const title = btn.getAttribute('data-title');
      handleAskAiClick(title);
    }
  });
}

// ---------- Init ----------

function initOddsToggle() {
  const toggleBtn = document.getElementById('toggle-odds');
  if (!toggleBtn) return;

  const savedSetting = localStorage.getItem('showOdds');
  if (savedSetting === 'false') {
    toggleBtn.checked = false;
    document.body.classList.add('hide-odds');
  } else {
    toggleBtn.checked = true;
    document.body.classList.remove('hide-odds');
  }

  toggleBtn.addEventListener('change', (e) => {
    if (e.target.checked) {
      document.body.classList.remove('hide-odds');
      localStorage.setItem('showOdds', 'true');
    } else {
      document.body.classList.add('hide-odds');
      localStorage.setItem('showOdds', 'false');
    }
  });
}

function setLastUpdated() {
  document.getElementById('last-updated').textContent =
    `Last checked ${today.toLocaleString(undefined, { hour: 'numeric', minute: '2-digit', month: 'short', day: 'numeric' })}`;
}

initOddsToggle();
initAiModelSelect();
initAskGeminiHandlers();
setLastUpdated();
loadHeadlines();
loadGolfLeaderboards();
loadYesterdayScores();
loadTodayGames();
loadTomorrowGames();

