// Daily Wrap — headlines, yesterday's scores, today's games.
// No API keys required: headlines come from headlines.json, generated by a
// scheduled GitHub Actions workflow (scripts/fetch-headlines.js) that fetches
// public RSS feeds server-side, where CORS doesn't apply. Sports data comes
// from ESPN's public scoreboard API, fetched directly from the browser.

// Fallback only — see fetchWithFallback, which tries the URL directly first
// and only reaches for these if that fails. ESPN allows cross-origin
// requests, so its scoreboard calls succeed direct and rarely need these.
const CORS_PROXIES = [
  (url) => `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,
  (url) => `https://api.codetabs.com/v1/proxy?quest=${encodeURIComponent(url)}`,
  // corsproxy.io removed: returned 403 on every single request (confirmed in
  // a browser console log, 2026-07-29) — a guaranteed-failing branch.
];

// Grouped by sport so the site stays organized even on days when only one
// sport has games (e.g. baseball-only stretches of the calendar). Covers the
// leagues with the heaviest US betting volume; a category with no games that
// day auto-collapses (see renderLeagueGroups) rather than disappearing.
// `siteSport` is the espn.com URL segment used to link team/fighter names to
// their real ESPN page (stats, roster, full schedule) instead of building a
// second copy of that here.
const LEAGUES = [
  { id: 'nfl', name: 'NFL', path: 'football/nfl', group: 'Football', siteSport: 'nfl' },
  { id: 'ncaaf', name: 'College Football', path: 'football/college-football', group: 'Football', siteSport: 'college-football' },
  { id: 'nba', name: 'NBA', path: 'basketball/nba', group: 'Basketball', siteSport: 'nba' },
  { id: 'wnba', name: 'WNBA', path: 'basketball/wnba', group: 'Basketball', siteSport: 'wnba' },
  { id: 'ncaab', name: 'College Basketball', path: 'basketball/mens-college-basketball', group: 'Basketball', siteSport: 'mens-college-basketball' },
  { id: 'mlb', name: 'MLB', path: 'baseball/mlb', group: 'Baseball', siteSport: 'mlb' },
  { id: 'nhl', name: 'NHL', path: 'hockey/nhl', group: 'Hockey', siteSport: 'nhl' },
  { id: 'epl', name: 'Premier League', path: 'soccer/eng.1', group: 'Soccer', siteSport: 'soccer' },
  { id: 'ucl', name: 'Champions League', path: 'soccer/uefa.champions', group: 'Soccer', siteSport: 'soccer' },
  { id: 'uel', name: 'Europa League', path: 'soccer/uefa.europa', group: 'Soccer', siteSport: 'soccer' },
  { id: 'laliga', name: 'La Liga', path: 'soccer/esp.1', group: 'Soccer', siteSport: 'soccer' },
  { id: 'seriea', name: 'Serie A', path: 'soccer/ita.1', group: 'Soccer', siteSport: 'soccer' },
  { id: 'bundesliga', name: 'Bundesliga', path: 'soccer/ger.1', group: 'Soccer', siteSport: 'soccer' },
  { id: 'ligue1', name: 'Ligue 1', path: 'soccer/fra.1', group: 'Soccer', siteSport: 'soccer' },
  { id: 'mls', name: 'MLS', path: 'soccer/usa.1', group: 'Soccer', siteSport: 'soccer' },
  { id: 'ufc', name: 'UFC', path: 'mma/ufc', group: 'Combat Sports', siteSport: 'mma' },
  // Boxing removed: ESPN returns a genuine HTTP 400 for the 'boxing/boxing'
  // path (direct, not via a proxy — confirmed in a browser console log), so
  // it only ever produced errors. No verified correct path to swap in.
];

const today = new Date();
const yesterday = new Date(today);
yesterday.setDate(today.getDate() - 1);
const tomorrow = new Date(today);
tomorrow.setDate(today.getDate() + 1);

function pad(n) { return String(n).padStart(2, '0'); }
function toYYYYMMDD(d) { return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}`; }
function longDate(d) { return d.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }); }

// A direct attempt either succeeds quickly or fails fast on CORS, so it gets
// a short leash; the free proxies are slower and get a longer one.
const DIRECT_TIMEOUT_MS = 6000;
const PROXY_TIMEOUT_MS = 20000;

async function fetchWithTimeout(url, timeoutMs = DIRECT_TIMEOUT_MS) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, { signal: controller.signal });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return res;
  } finally {
    clearTimeout(timer);
  }
}

async function fetchWithFallback(url) {
  // Direct first, on its own — ESPN allows cross-origin requests, so this
  // succeeds for essentially every call and the proxies below go unused.
  try {
    const res = await fetchWithTimeout(url);
    return await res.json();
  } catch {
    // Fall through to the proxies for the rare direct failure.
  }

  const attempts = CORS_PROXIES.map((makeProxyUrl) =>
    fetchWithTimeout(makeProxyUrl(url), PROXY_TIMEOUT_MS).then((res) => res.json())
  );
  try {
    return await Promise.any(attempts);
  } catch (aggregateErr) {
    throw aggregateErr.errors?.[0] || aggregateErr;
  }
}

// ---------- Headlines ----------

function relativeTime(ts) {
  const mins = Math.round((Date.now() - ts) / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins} min ago`;
  const hours = Math.round(mins / 60);
  if (hours < 24) return `${hours} hr ago`;
  const days = Math.round(hours / 24);
  return `${days} day${days === 1 ? '' : 's'} ago`;
}

function renderSourceBody(source) {
  const items = source.items || [];
  if (items.length === 0) return '<p class="empty">Couldn\'t load.</p>';
  const staleNote = !source.ok && source.updatedAt
    ? `<p class="empty">Saved copy from ${relativeTime(new Date(source.updatedAt).getTime())} — couldn't refresh just now.</p>`
    : '';
  return staleNote + '<ul class="headline-list">' + items.map((it) =>
    `<li><a href="${it.link}" target="_blank" rel="noopener noreferrer">${it.title}</a></li>`
  ).join('') + '</ul>';
}

async function loadHeadlines() {
  const container = document.getElementById('headlines-list');
  const sub = document.getElementById('headlines-sub');
  sub.textContent = longDate(today);
  container.innerHTML = '<p class="loading">Loading headlines…</p>';

  let data;
  try {
    // no-store: this file is regenerated every ~30 min by a GitHub Actions
    // workflow, and we want the current copy, not one the browser cached.
    const res = await fetch('headlines.json', { cache: 'no-store' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    data = await res.json();
  } catch (err) {
    console.warn('Failed to load headlines.json:', err);
    container.innerHTML = '<p class="error">Couldn\'t load headlines right now. Try refreshing the page.</p>';
    return;
  }

  container.innerHTML = '';
  for (const source of data.sources || []) {
    const el = document.createElement('details');
    el.className = 'source-group';
    if ((source.items || []).length > 0) el.open = true;
    el.innerHTML = `<summary><h3>${source.name}</h3></summary>` +
      `<div class="source-group-body">${renderSourceBody(source)}</div>`;
    container.appendChild(el);
  }
}

// ---------- Sports ----------

// A competitor is either a team (most sports) or an athlete (fights). Either
// way, link its name to the real ESPN page for that team/fighter — building
// and keeping our own stats/roster pages in sync would be its own project.
function extractParticipant(c, league) {
  const isAthlete = !!c.athlete && !c.team;
  const entity = c.team || c.athlete;
  const name = entity?.displayName || entity?.shortDisplayName || entity?.name || 'TBD';
  const link = entity?.id
    ? `https://www.espn.com/${league.siteSport}/${isAthlete ? 'player' : 'team'}/_/id/${entity.id}`
    : null;
  return { name, score: c.score, link };
}

function normalizeEvent(ev, league) {
  const comp = ev.competitions?.[0];
  const statusType = comp?.status?.type || {};
  const competitors = comp?.competitors || [];
  const home = competitors.find((c) => c.homeAway === 'home') || competitors[0];
  const away = competitors.find((c) => c.homeAway === 'away') || competitors[1];
  return {
    date: ev.date,
    state: statusType.state, // 'pre' | 'in' | 'post'
    completed: !!statusType.completed,
    statusDetail: statusType.shortDetail || statusType.detail || '',
    home: home ? extractParticipant(home, league) : null,
    away: away ? extractParticipant(away, league) : null,
  };
}

async function fetchScoreboard(league, date) {
  const url = `https://site.api.espn.com/apis/site/v2/sports/${league.path}/scoreboard?dates=${toYYYYMMDD(date)}`;
  try {
    const data = await fetchWithFallback(url);
    return (data.events || []).map((ev) => normalizeEvent(ev, league));
  } catch (err) {
    console.warn(`Scoreboard fetch failed for ${league.name}:`, err);
    return null; // signals a failed fetch, distinct from "no games"
  }
}

function groupBy(list, keyFn) {
  const map = new Map();
  for (const item of list) {
    const key = keyFn(item);
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(item);
  }
  return map;
}

function renderLeagueGroups(container, leagueResults, renderGame, emptyLabel) {
  if (leagueResults.every((r) => r.events === null)) {
    container.innerHTML = '<p class="error">Couldn\'t load sports data right now. Try refreshing the page.</p>';
    return;
  }

  const byGroup = groupBy(leagueResults, (r) => r.league.group);
  container.innerHTML = '';
  for (const [groupName, leagues] of byGroup) {
    const hasGames = leagues.some((r) => r.events && r.events.length > 0);
    const groupEl = document.createElement('details');
    groupEl.className = 'league-group';
    if (hasGames) groupEl.open = true;
    let groupHtml = `<summary><h3>${groupName}</h3></summary><div class="league-group-body"><ul class="game-list">`;
    for (const { league, events } of leagues) {
      if (events === null) {
        groupHtml += `<li class="game-row muted-row"><span class="team-name">${league.name}</span><span class="game-status">Couldn't load</span></li>`;
      } else if (events.length === 0) {
        groupHtml += `<li class="game-row muted-row"><span class="team-name">${league.name}</span><span class="game-status">${emptyLabel}</span></li>`;
      } else {
        groupHtml += events.map((ev) => renderGame(ev, league)).join('');
      }
    }
    groupHtml += `</ul></div>`;
    groupEl.innerHTML = groupHtml;
    container.appendChild(groupEl);
  }
}

function nameHtml(participant) {
  return participant.link
    ? `<a href="${participant.link}" target="_blank" rel="noopener noreferrer">${participant.name}</a>`
    : participant.name;
}

function renderYesterdayGame(ev, league) {
  if (!ev.completed) return '';
  const away = ev.away, home = ev.home;
  return `<li class="game-row">
    <div class="game-teams">
      <div class="team-row"><span class="team-name">${league.name} · ${nameHtml(away)}</span><span class="team-score">${away.score}</span></div>
      <div class="team-row"><span class="team-name">${nameHtml(home)}</span><span class="team-score">${home.score}</span></div>
    </div>
    <span class="game-status">${ev.statusDetail || 'Final'}</span>
  </li>`;
}

function renderScheduledGame(ev, league) {
  const away = ev.away, home = ev.home;
  const time = new Date(ev.date).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
  let statusHtml;
  if (ev.state === 'in') {
    statusHtml = `<span class="game-status live">${ev.statusDetail || 'Live'}</span>`;
  } else if (ev.state === 'post') {
    statusHtml = `<span class="game-status">${ev.statusDetail || 'Final'}</span>`;
  } else {
    statusHtml = `<span class="game-status">${time}</span>`;
  }
  const showScores = ev.state !== 'pre';
  return `<li class="game-row">
    <div class="game-teams">
      <div class="team-row"><span class="team-name">${league.name} · ${nameHtml(away)}</span>${showScores ? `<span class="team-score">${away.score}</span>` : ''}</div>
      <div class="team-row"><span class="team-name">${nameHtml(home)}</span>${showScores ? `<span class="team-score">${home.score}</span>` : ''}</div>
    </div>
    ${statusHtml}
  </li>`;
}

async function loadYesterdayScores() {
  document.getElementById('yesterday-date').textContent = longDate(yesterday);
  const container = document.getElementById('yesterday-scores-list');
  const results = await Promise.all(LEAGUES.map(async (league) => {
    const events = await fetchScoreboard(league, yesterday);
    const completed = events ? events.filter((e) => e.completed) : null;
    return { league, events: completed };
  }));
  renderLeagueGroups(container, results, renderYesterdayGame, 'No games');
}

async function loadGamesFor(dateLabelId, listId, date) {
  document.getElementById(dateLabelId).textContent = longDate(date);
  const container = document.getElementById(listId);
  const results = await Promise.all(LEAGUES.map(async (league) => {
    const events = await fetchScoreboard(league, date);
    return { league, events };
  }));
  renderLeagueGroups(container, results, renderScheduledGame, 'No games scheduled');
}

async function loadTodayGames() {
  await loadGamesFor('today-date', 'today-games-list', today);
}

async function loadTomorrowGames() {
  await loadGamesFor('tomorrow-date', 'tomorrow-games-list', tomorrow);
}

// ---------- Golf Leaderboards ----------

const GOLF_TOURS = [
  { id: 'pga', name: 'PGA TOUR', path: 'golf/pga', siteSport: 'golf' },
  { id: 'lpga', name: 'LPGA Tour', path: 'golf/lpga', siteSport: 'golf' },
  { id: 'liv', name: 'LIV Golf', path: 'golf/liv', siteSport: 'golf' },
];

function formatGolfDates(startStr, endStr) {
  try {
    const s = new Date(startStr);
    const e = endStr ? new Date(endStr) : s;
    const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const startMonth = MONTHS[s.getUTCMonth()];
    const endMonth = MONTHS[e.getUTCMonth()];
    const startDay = s.getUTCDate();
    const endDay = e.getUTCDate();
    const year = e.getUTCFullYear();
    if (startMonth === endMonth) {
      return `${startMonth} ${startDay} – ${endDay}, ${year}`;
    }
    return `${startMonth} ${startDay} – ${endMonth} ${endDay}, ${year}`;
  } catch {
    return '';
  }
}

async function loadGolfLeaderboards() {
  const container = document.getElementById('golf-list');
  if (!container) return;

  const results = await Promise.all(GOLF_TOURS.map(async (tour) => {
    const url = `https://site.api.espn.com/apis/site/v2/sports/${tour.path}/scoreboard`;
    try {
      const data = await fetchWithFallback(url);
      return { tour, data };
    } catch (err) {
      console.warn(`Golf fetch failed for ${tour.name}:`, err);
      return { tour, data: null };
    }
  }));

  if (results.every((r) => r.data === null)) {
    container.innerHTML = '<p class="error">Couldn\'t load golf data right now. Try refreshing the page.</p>';
    return;
  }

  container.innerHTML = '';

  for (const { tour, data } of results) {
    const groupEl = document.createElement('details');
    groupEl.className = 'league-group golf-card';

    const events = data?.events || [];
    if (events.length > 0) groupEl.open = true;

    if (!data || events.length === 0) {
      groupEl.innerHTML = `
        <summary><div class="golf-summary-header"><h3>${tour.name}</h3><span class="game-status">Scheduled</span></div></summary>
        <div class="league-group-body">
          <p class="empty">No tournament scheduled this week.</p>
        </div>`;
      container.appendChild(groupEl);
      continue;
    }

    const event = events[0];
    const comp = event.competitions?.[0] || {};
    const statusType = comp.status?.type || event.status?.type || {};
    const isLive = statusType.state === 'in';
    const isCompleted = statusType.state === 'post' || statusType.completed;

    let statusText = '';
    let statusBadgeClass = 'game-status';
    if (isLive) {
      statusBadgeClass = 'game-status live';
      statusText = '● LIVE · ' + (statusType.detail || statusType.shortDetail || 'In Progress');
    } else if (isCompleted) {
      statusText = 'Final · ' + (statusType.detail || statusType.shortDetail || 'Complete');
    } else {
      if (event.date) {
        const startDate = new Date(event.date);
        const dateFormatted = startDate.toLocaleDateString('en-US', {
          timeZone: 'UTC',
          weekday: 'short',
          month: 'short',
          day: 'numeric'
        });
        statusText = `Scheduled · Starts ${dateFormatted}`;
      } else {
        statusText = 'Scheduled';
      }
    }

    const venue = comp.venue ? `${comp.venue.fullName || ''}${comp.venue.address?.city ? ' · ' + comp.venue.address.city : ''}` : '';
    const dateRange = event.date ? formatGolfDates(event.date, event.endDate) : '';

    const competitors = comp.competitors || [];
    const showLimit = 8;
    const tournamentId = `${tour.id}-leaderboard`;

    let html = `
      <summary>
        <div class="golf-summary-header">
          <h3>${tour.name}</h3>
          <span class="${statusBadgeClass}">${statusText}</span>
        </div>
      </summary>
      <div class="league-group-body golf-body">
        <div class="golf-tourney-meta">
          <div class="golf-tourney-title">${event.name}</div>
          <div class="golf-tourney-sub">${dateRange}${venue ? ' · ' + venue : ''}</div>
        </div>`;

    if (competitors.length === 0) {
      html += `<p class="empty" style="margin-top:0.75rem;">Field and tee times will be available closer to the tournament start.</p>`;
    } else {
      html += `
        <div class="golf-table-wrap">
          <table class="golf-table" id="${tournamentId}">
            <thead>
              <tr>
                <th class="col-pos">Pos</th>
                <th class="col-player">Player</th>
                <th class="col-score">Score</th>
                <th class="col-thru">Thru</th>
              </tr>
            </thead>
            <tbody>`;

      competitors.forEach((c, idx) => {
        const isHidden = idx >= showLimit;
        const pos = c.status?.position?.displayName || c.order || (idx + 1);
        const athlete = c.athlete || {};
        const name = athlete.displayName || athlete.fullName || 'Golfer';
        const athleteId = athlete.id || c.id;
        const link = athleteId
          ? `https://www.espn.com/golf/player/_/id/${athleteId}`
          : null;

        const playerHtml = link
          ? `<a href="${link}" target="_blank" rel="noopener noreferrer">${name}</a>`
          : name;

        const flagImg = athlete.flag?.href
          ? `<img class="golf-flag" src="${athlete.flag.href}" alt="${athlete.flag.alt || ''}" title="${athlete.flag.alt || ''}">`
          : '';

        const score = c.score || 'E';
        const scoreClass = score.startsWith('-') ? 'score-under' : (score.startsWith('+') ? 'score-over' : 'score-even');

        let thru = c.status?.type?.shortDetail || c.status?.detail || '';
        if (c.status?.period && !thru) thru = `R${c.status.period}`;

        html += `
          <tr class="golf-row ${isHidden ? 'golf-row-extra hidden' : ''}">
            <td class="col-pos">${pos}</td>
            <td class="col-player">${flagImg}${playerHtml}</td>
            <td class="col-score ${scoreClass}">${score}</td>
            <td class="col-thru">${thru}</td>
          </tr>`;
      });

      html += `</tbody></table></div>`;

      if (competitors.length > showLimit) {
        html += `
          <button type="button" class="golf-expand-btn" data-target="${tournamentId}">
            Show full field (${competitors.length} golfers)
          </button>`;
      }
    }

    html += `</div>`;
    groupEl.innerHTML = html;
    container.appendChild(groupEl);
  }

  container.querySelectorAll('.golf-expand-btn').forEach((btn) => {
    btn.addEventListener('click', (e) => {
      const targetId = e.currentTarget.getAttribute('data-target');
      const table = document.getElementById(targetId);
      if (!table) return;
      const hiddenRows = table.querySelectorAll('.golf-row-extra');
      const isExpanded = btn.classList.contains('expanded');

      hiddenRows.forEach((row) => {
        if (isExpanded) {
          row.classList.add('hidden');
        } else {
          row.classList.remove('hidden');
        }
      });

      if (isExpanded) {
        btn.classList.remove('expanded');
        const totalRows = table.querySelectorAll('tbody tr').length;
        btn.textContent = `Show full field (${totalRows} golfers)`;
      } else {
        btn.classList.add('expanded');
        btn.textContent = 'Show top 8 only';
      }
    });
  });
}

// ---------- Init ----------

function setLastUpdated() {
  document.getElementById('last-updated').textContent =
    `Last checked ${today.toLocaleString(undefined, { hour: 'numeric', minute: '2-digit', month: 'short', day: 'numeric' })}`;
}

setLastUpdated();
loadHeadlines();
loadGolfLeaderboards();
loadYesterdayScores();
loadTodayGames();
loadTomorrowGames();
